### ISSUE TITLE
Error: `require': cannot load such file

### ISSUE THREAD

**Issue by RRMoelker** [cesarferreira/react-native-logcat#2]
Hello,

The program does not start on my setup. I installed the package with:

```
gem install react-native-logcat
```

After that when I run `react-native-logcat` I get the following error:

```
$ react-native-logcat
/usr/local/Cellar/ruby/2.2.3/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- bundler/setup (LoadError)
    from /usr/local/Cellar/ruby/2.2.3/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
    from /usr/local/lib/ruby/gems/2.2.0/gems/react-native-logcat-0.2.4/bin/react-native-logcat:3:in `<top (required)>'
    from /usr/local/bin/react-native-logcat:23:in `load'
    from /usr/local/bin/react-native-logcat:23:in `<main>'
```

It seems another dependency is ruby bundler. After installing the program works. Install using:

```
gem install bundler
```

Suggest updating README to reflect dependency.

**Comment by cesarferreira** [comment]
Hey mate, thanks for noticing!
Just fixed it on `0.2.5` !
I had bundler as a development dependency, instead of a normal dependency!
